site:
  title: 'Moodle'
  start_page: manual::index.adoc
content:
  sources:
    - url: .
      start_path: ./manual/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable