= Группы, потоки

Зачисленный на курс пользователь становится его участником, т. е. участником учебного процесса, обеспечиваемого данным курсом. Чтобы отдельным объединениям участников поручать различную деятельность в учебном процессе, из каждого такого объединения формируется отдельная учебная группа. А чтобы выполнять коллективные действия над несколькими группами, эти группы объединяют в потоки.

image::images/[Рис. 5. Раздел "Группы"]

В блоке Настройки выберите пункт *Управление курсом=> Пользователи => Группы*. В соответствующих вкладках данного раздела настроек Вы можете создать группы и потоки или ознакомиться с их перечнем. 

В левой половине окна отображаются созданные в курсе группы: «Название группы (количество участников группы)». В правой половине окна отображаются участники выбранной группы (в данном случае участники выделенной группы 2). 

Для создания групп во вкладке «*Группы*», нужно нажать кнопку «*Создать группу*», и в появившейся форме ввести название группы (остальные поля оставляем пустыми). После ввода данных нажимаем кнопку «Сохранить». Для изменения настроек группы выделите ее, кликнув по названию группы, далее нажмите кнопку «*Редактировать настройки*», внесите соответствующие изменения и сохраните их. 

Для редактирования участников группы нужно сначала выделить ее, затем нажать кнопку «*Добавить/удалить участников*». 

image::images/[Рис. 6. Страница "Добавить / удалить участников группы"]

* [.underline]#Для добавления участников в группу:# в колонке «Возможные участники» выберите студентов (выбор нескольких пользователей можно осуществить, удерживая клавишу CTRL), далее нажмите кнопку «Добавить».
* [.underline]#Для удаления участников из группы:# в колонке «Участники группы» выберите студентов (выбор нескольких пользователей можно осуществить, удерживая клавишу CTRL), далее нажмите кнопку «Удалить».

Для возвращения на страницу «Группы» используйте кнопку «*Назад к группам*». 

Во вкладке «*Потоки*» (рис.7) из созданных групп создаются и формируются потоки. Для создания потока необходимо нажать кнопку «*Создать поток*». Далее в появившейся форме ввести название потока (остальные поля оставляем пустыми). После сохранения введенного результата страница обновится, и на ней отобразится список всех потоков курса с содержащимися в нем группами и количеством назначенных элементов курса. 

Для каждого потока доступны управляющие кнопки (в столбце «Редактировать»): - Редактировать,  - Удалить,  - Показать группы в потоке.

image::images/[Рис. 7. Вкладка "Потоки" раздела "Группы"]

image::images/[Рис. 8. Вкладка "Обзор" раздела "Группы"]

Во вкладке «*Обзор*» (рис.8) Вы можете ознакомиться с созданной Вами структурой пользователей. Также на этой странице Вам доступен фильтр групп. 