= Введение

Moodle (Modular Object-Oriented Dynamic Learning Environment - модульная объектно
ориентированная динамическая обучающая среда) — это свободная система управления 
обучением, ориентированная, прежде всего, на организацию взаимодействия между 
преподавателем и учениками. 

Moodle относится к классу LMS (Learning Management System) — систем управления 
обучением. В нашей стране подобное программное обеспечение чаще называют системами 
дистанционного обучения (СДО), так как именно при помощи подобных систем во многих вузах 
организовано дистанционное обучение. LMS Moodle дает преподавателю обширный 
инструментарий для представления учебно-методических материалов курса, проведения 
теоретических и практических занятий, организации учебной деятельности как индивидуальной, 
так и групповой. 

Для использования Moodle достаточно иметь web-браузер, что делает использование этой 
учебной среды удобной как для преподавателя, так и для обучающихся.

Moodle дает возможность проектировать, создавать и в дальнейшем управлять ресурсами 
информационно-образовательной среды. Система имеет удобный интуитивно понятный 
интерфейс. Преподаватель самостоятельно, прибегая только к помощи справочной системы, 
может создать электронный курс и управлять его работой. Можно вставлять таблицы, схемы, 
графику, видео, флэш и др. Редактирование содержания курса проводится автором курса в 
произвольном порядке и может легко осуществляться прямо в процессе обучения. Очень легко 
добавляются в электронный курс различные элементы: лекция, задание, форум, глоссарий, вики, 
чат и т.д. По результатам выполнения учениками заданий преподаватель может выставлять оценки 
и давать комментарии. Таким образом, Moodle является центром создания учебного материала и 
обеспечения интерактивного взаимодействия между участниками учебного процесса. 

Ориентированная на дистанционное образование, система управления обучением Moodle 
обладает большим набором средств коммуникации. Это не только электронная почта и обмен 
вложенными файлами с преподавателем, но и форум (общий новостной на главной странице, а 
также различные частные форумы), чат, обмен личными сообщениями, ведение блогов. 

В LMS Moodle имеется обширный инструментарий для создания тестов и проведения 
обучающего и контрольного тестирования. Поддерживается несколько типов вопросов в тестовых 
заданиях (множественный выбор, на соответствие, верно/неверно, короткие ответы, эссе и др.). 
Moodle также предоставляет много функций, облегчающих обработку тестов. В системе 
содержатся развитые средства статистического анализа результатов тестирования и, что очень 
важно, сложности отдельных тестовых вопросов для обучающихся. 