= Настройки курса

Для изменения настроек курса преподавателю необходимо обратиться к блоку Настройки. В данном блоке отображается меню «*Управление курсом*», выбираем пункт «*Редактировать настройки*». На странице редактирования настройки разбиты на 8 классов. По щелчку на названии класса настроек разворачиваются все настройки, содержащиеся в данном классе. Развернуть все настройки одновременно можно, используя одноименную команду, справа над формой редактирования настроек. 

Рассмотрим основные настройки курса более детально. 

* _Общее_:
** Полное название курса – заполняется при отправке запроса, доступно для редактирования в любое время.
** Краткое название курса – заполняется при отправке запроса, доступно для редактирования в любое время.
** Категория курса – категория выбирается только при отправке запроса. В дальнейшем изменить это поле Вы не можете. При необходимости изменения категории курса нужно обратиться к администратору.
** Доступность – параметр, определяющий будет ли курс отображаться в списке курсов. Пользователи, кроме преподавателей и администраторов, не смогут войти в скрытый курс.
** Дата начала курса – параметр, определяющий начальную дату, с которой будут доступны отчеты по элементам курса. *В данном параметре необходимо указать дату начала обучения по дисциплине*.
** Идентификационный номер курса – параметр, необходимый только при использовании курса во внешних системах, он нигде не отображается на сайте Moodle. Если у вас есть официальное кодовое обозначение данного курса, то используйте его; в противном случае оставьте поле пустым.

* _Описание_:
** Описание курса – заполняется при отправке запроса, доступно для редактирования в любое время.
** Файлы описания курса – эти файлы (например, изображения) отображаются в списке курсов рядом с описанием.

* _Формат курса_:
** Формат – параметр, определяющий представление страницы курса. В рамках электронной информационно-образовательной среды формат курса должен быть обязательно «Разделы по темам» (данная настройка установлена по умолчанию).
** Количество разделов. Вы можете изменить количество разделов курса, используя данный пункт настроек или напрямую со страницы курса в режиме редактирования. По умолчанию создаются курсы с 10 разделами.
** Отображение скрытых разделов. Этот параметр определяет, будут ли скрытые разделы отображаться для студентов в свернутом виде или они будут полностью скрыты.
** Представление курса. Этот параметр определяет, будет ли весь курс отображаться на одной странице или будет разделен на несколько страниц.

* _Внешний вид_ (если у вас нет каких-либо предпочтений в данном классе настроек, этот пункт можно не трогать и оставить по умолчанию): 
** Принудительный язык: не устанавливать принудительно (по умолчанию), русский, английский.
** Количество отображаемых новостей. По умолчанию установлено 5.
** Показывать журнал оценок студентам. Данный параметр всегда должен быть равен «Да».
** Показывать отчеты о деятельности. Отчеты о деятельности доступны для каждого участника и отображают результаты его работы в курсе. Отчет может содержать подробный список действий пользователя, например, сообщения форума или представленные задания, эти отчеты также содержат записи журнала событий. Этот параметр определяет, сможет ли студент просматривать отчеты о своей собственной деятельности на странице своего профиля. По умолчанию – параметр установлен в значении «Нет».

* _Файлы и загрузки_ (аналогично предыдущему классу, можно использовать настройки по
умолчанию):
** Максимальный размер загружаемого файла – эта установка определяет максимальный размер файла, который может быть загружен в курс. Она не может превышать значения, установленного администратором для всего сайта (50Мбайт). У отдельных элементов курса тоже есть настройка максимального размера загружаемого файла для
дополнительного ограничения этого размера.

* _Группы_. Здесь настраиваются параметры:
** Групповой режим. Имеется 3 варианта:
*** Нет групп - все участники являются членами одного большого сообщества.
*** Изолированные группы - участники каждой группы работают только в пределах своей группы, другие группы им не видны.
*** Видимые группы - участники каждой группы работают только в пределах своей группы, но могут видеть другие группы.

_Примечание._ Групповой режим, определенный на уровне курса, является режимом по умолчанию 
для всех элементов, создаваемых в курсе. Однако для каждого элемента, поддерживающего 
групповой режим, можно указать его собственный групповой режим. 

** Принудительный групповой режим. Если параметр активен (т.е. если используется вариант «Да» в данной настройке), то установленный групповой режим применяется для всех элементов курса. Настройки группового режима каждого элемента игнорируются.
** Поток по умолчанию – если заданы потоки пользователей, то установка определяет, какому потоку доступны по умолчанию все элементы курса.

_Примечание._ При назначении группового режима («изолированные группы», «видимые группы») 
для корректной работы необходимо сформировать из этих групп поток и назначить его потоком по 
умолчанию. Это касается также настроек группового режима для элементов курса. 

После внесения изменений не забываем нажать на кнопку «*Сохранить и показать*».