= Основные понятия

Для целостного понимания принципов работы системы введем в рассмотрение базисные термины. В первую очередь введем понятие «роли» пользователя. 

*Роль* – это коллекция полномочий, делегируемых конкретным пользователям, именно роль определяет то, что пользователю разрешено делать на сайте. 

В системе существуют пять основных ролей. Это администраторы, создатели курсов, преподаватели, студенты и гости. Заметим, что количество ролей может быть изменено в зависимости от потребностей. 

*Преподаватель* курса имеет права на проведение обучения (отправление запросов на создание курса, управление курсом, оценивание студентов в своем курсе и др.). 

*Студент* имеет права на просмотр материалов курса и выполнение различного рода проверочных работ, назначенных преподавателем, а также имеет доступ к своей успеваемости. 

Ввиду того, что Moodle – система с гибкой настройкой прав, роли могут назначаться не глобально, а в рамках определенного контекста. Определим контекст как некоторое пространство в Moodle. 

Мы с Вами рассмотрим такие варианты контекста, как: 

* *Категория курсов* – это группа курсов, объединенных по определенному критерию. 

* *Курс* – основная обучающая область, где преподаватель представляет материалы студентам. В рамках нашей концепции – это обучающая область, выделенная под дисциплину. 

* *Действие* – это инструменты Moodle, используемые для представления какого-либо материала, т.е. это то, что можно добавить в содержимое курса. 

* *Блок* – информационные элементы, которые могут быть добавлены слева или справа на домашнюю страницу курса. Блоки дают пользователю дополнительную информацию или ссылки и подобны «вспомогательным устройствам», приспособленным для облегчения работы в режиме онлайн. 

Выделим 2 вида действий: *ресурс* и *элемент* (интерактивное действие). 

*Ресурс* – действие, которое преподаватель предлагает выполнить студенту в курсе индивидуально (самостоятельно). Ресурсы предназначены для представления статичных материалов курса. 

*Элемент* (интерактивное действие) – это то, что студент будет выполнять во взаимодействии с другими студентами и/или преподавателем, т.е. интерактивно. Это средства вовлечения студентов в активное обучение. 

Для корректного проектирования всех взаимодействий в рамках курса введем понятия для слушателей курса. 

*Участники курса* – это все пользователи, записанные на данный курс вне зависимости от определенной им роли, т.е. все преподаватели и студенты курса в совокупности. Участники в рамках курса могут быть поделены на сообщества. 

*Группа* – часть студентов курса, которым поручается выполнять что-то в процессе обучения в данном курсе. 

*Поток* – набор групп в курсе, т.е. объединение нескольких групп. Служит для выполнения массовых действий сразу со всеми еѐ членами. 

Для реализации электронного журнала введем понятие оценок курса. 

*Оценки* – это модуль системы Moodle для контроля и отображения хода обучения в течение 
курса. 

_Примечание_. Элементы (интерактивные действия) обладают настройками оценивания и / или 
работы в группах.