= Разделы курса

Разделы курса отображаются в центре страницы курса. Число разделов курса Вы задаете в настройках курса. Но если в творческом процессе Вы решили изменить количество разделов, это возможно сделать без обращения к настройкам, щелчком по иконкам « (плюс)» или «(минус)» внизу страницы курса, когда режим редактирования включѐн. 

Каждый раздел курса имеет атрибуты: Название раздела и Описание. Описание - это небольшой текст, рассказывающий студентам о дальнейшей деятельности в рамках этого раздела (темы). Текст отображается на странице курса под названием раздела. 

По умолчанию разделы курса называются «Тема №п/п» и не содержат описания. В режиме редактирования для каждого раздела доступно меню «*Редактировать*» (рис.10).

На рис. 11 представлена форма для ввода названия и описания темы, она становится доступна после выбора пункта «Редактировать тему» меню редактирования раздела. Для ввода названия раздела нужно снять галочку с флажка «Использовать название раздела по умолчанию».

image::images/[Рис. 10. Меню «Редактировать» раздела курса]

image::images/[Рис. 11. Редактирование темы]

Команда «Выделить» меню редактирования раздела позволяет выделить тему как текущую (раздел выделяется цветом).  

Чтобы отредактировать только название раздела курса (темы): 

* Включите режим редактирования.
* Щѐлкните иконку редактирования за заголовком раздела . 
* Введите в появившееся текстовое поле текст и нажмите клавишу Enter.

Чтобы переместить раздел курса:

* Включите режим редактирования.
* Перетащите раздел, куда вам нужно, используя управляющую кнопку «Переместить» .