= Управление курсом

= Запрос на создание курса

Для добавления курса Вам необходимо создать запрос. Для этого на главной странице сайта в основном меню выберите ссылку «*Запрос курса*», открывающую страницу запроса нового курса.

_Примечание_. Еще один способ открыть страницу запроса курса - нажать кнопку «Отправить запрос на создание курса» внутри какой-либо из категорий. Однако при этом следует знать, что поле «Категория курса» на странице запроса автоматически заполняется категорией по умолчанию, а не выбранной вами категорией (категория по умолчанию устанавливается администратором). 

Далее приступаем к заполнению формы запроса. Поля формы разделены на два раскрывающихся класса: 

1. Подробности о запрошенном Вами курсе (данные атрибуты запроса в дальнейшем переходят в настройки Вашего курса, поэтому необходимо заполнять информацию корректно):

*Полное название Курса** – отображается вверху каждой страницы курса и в списке курсов. 

*Краткое название курса** – отображается в элементах навигации и используется в теме сообщений электронной почты. 

*Категория курса** – этот параметр определяет категорию, в которую курс будет добавлен. Выбирается из выпадающего списка созданных в системе категорий. 

*Описание курса* – краткое резюме Вашего курса, которое отображается в списке курсов. Поиск курсов осуществляется по их названиям и по их описаниям. 

2. Причины создания курса:

*Дополнительная информация, которая может помочь администратору принять решение по этому запросу**. Здесь Вы указываете обоснование для одобрения запроса: направление подготовки, форма обучения. 

_Примечание_. Поля, отмеченные звездочками, являются обязательными для заполнения. 

Заполнив все нужные поля формы, нажимаем кнопку «*Отправить запрос на создание курса*». 

После рассмотрения администратором запроса на Вашу электронную почту (указанную в профиле) будет направлено письмо. 

* *В случае одобрения* – письмо со ссылкой на новый (пустой) курс. В новом курсе по умолчанию создается 10 разделов.
* *В случае отклонения запроса* – письмо с указанием причины отказа. При подобном исходе запроса Вам нужно исправить замечания администратора и отправить запрос повторно.

